# Site settings
baseurl = "https://strongpictures.github.io/"
languageCode = "pl"
title = "Szymon Sokołowski – Fotografia i retusz"
theme = "multiverse"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

assetsDir = "assets"
contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
# Meta
title = "Szymon Sokołowski"
subtitle = "fotografia i retusz"
author = "Szymon Sokołowski"
description = ""
keywords = ""

# Social Media
twitter = ""
facebook = ""
instagram = "https://www.instagram.com/meta_strong_fiction/"
linkedIn = ""
