# Site settings
baseurl = "https://strongpictures.github.io/"
languageCode = "pl"
title = "Szymon Sokołowski – Fotografia i retusz"
theme = "multiverse"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

assetsDir = "assets"
contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
# Meta
title = "Szymon Sokołowski"
subtitle = "fotografia i retusz"
author = "Szymon Sokołowski"
description = "Profesjonalna fotografia i retusz beauty."
keywords = "fotografia, retusz"

aboutMe = """
W fotografii i retuszu najbardziej interesuje mnie beauty i fashion.
Aktualnie działam też w obszarze fotografii stockowej, produktowej, dokumentacji dzieł sztuki oraz wystaw.
Mieszkam w Krakowie.

Fotografia jest medium, w którym najbardziej lubię pracować, bo daje mi przestrzeń na ekspresję mojego spojrzenia.
Zanim odkryłem, że jest to kierunek w którym chce się realizować, studiowałem filozofię przez 5 lat, a wcześniej inżynierię produkcji. W fotografii zaczynałem od aparatu analogowego, by z czasem odkryć, że fotografia cyfrowa daje nieporównywalnie większe możliwości.
"""

# Social Media
twitter = ""
facebook = ""
instagram = "https://www.instagram.com/meta_strong_fiction/"
linkedIn = ""
